# Generated by Django 3.0.3 on 2020-09-02 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
