# Generated by Django 3.0.3 on 2020-10-21 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_historicalbookinstance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalBookInstance',
        ),
    ]
